### PR TITLE
fix: mimic reakit behaviour on popover trigger hover

### LINKED ISSUE #833: Popover not working correctly with `triggerMode="hover"` and `modal=true`
###  Describe the bug

When using `Popover`'s `usePopoverState` with the following options : `triggerMethod: "hover"` and `modal: true`, the popover never disappears after `Popover` has shown.

### To Reproduce

Just add the options in the playground of Popover's documentation.

### Expected behavior

Popover should disappear when `Popover.Trigger` or `Popover` are not hovered anymore.

### Environment

- `@welcome-ui/popover` 3.0.0

### PR DESCRIPTION
**Pull request by P1X3L**
Fixes #833

Signed-off-by: Paul-Xavier Ceccaldi <pix@wttj.co>

### CODE REVIEW

File: packages/Popover/Trigger.js [hunk 1]
```diff
@@ -1,17 +1,54 @@
...
+  }, [hoverable, popoverRef, rest, showPopover])
+
+  useLayoutEffect(() => {
+    const disclosure = disclosureRef.current
+    if (hoverable && disclosure) {
+      // add listeners on mount
+      disclosure.addEventListener('mouseenter', showPopover)
+      disclosure.addEventListener('mouseleave', hidePopover)
+      return () => {
+        // remove listeners on unmounte
```
Comment (P1X3L) [inline packages/Popover/Trigger.js:43]: 🙈 "unmounte"

**Review by guillaumewttj — APPROVED** [review]
👏

**Review by theo-mesnil — APPROVED** [review]

**Review by anucreative — APPROVED** [review]
