### PR TITLE
fix: only display year selector when Datepicker shows months only

### LINKED ISSUE #2366: A Datepicker that only displays months should have a different custom header
### [Design] For which Figma library?

None

### For which component/foundations?

DatePicker

### Prioritization

Low 🏖️

### Current Behavior

When we set the `showMonthYearPicker` prop to a Datepicker, it only displays months.
However, the custom header displays a selector for months as well as a selector for years.

### Expected Behavior

The default behavior should display a custom header with a selector only for years. The "previous" and "next" arrows should change the year and not the month.

### Current behavior

Screenshot 2023-11-27 at 16 29 00

### Expected behavior

Screenshot 2023-11-27 at 16 29 27

### [Tech] Welcome UI Version

_No response_

### [Tech] Browser

_No response_

### [Tech] Operating System

MacOS

### PR DESCRIPTION
**Pull request by simon-hv**
Fixes #2366

### CODE REVIEW

File: packages/DateTimePickerCommon/src/datePickerStyles.ts [hunk 1]
```diff
@@ -302,9 +302,12 @@ export const datePickerStyles = css`
 
   .react-datepicker__month .react-datepicker__month-text,
   .react-datepicker__month .react-datepicker__quarter-text {
-    display: inline-block;
+    display: inline-flex;
     width: 4rem;
+    height: 2rem;
```
Comment (simon-hv) [inline packages/DateTimePickerCommon/src/datePickerStyles.ts:307]: I did this to improve the style when we display months:

### Before
Screenshot 2023-11-27 at 17 53 37

### After
Screenshot 2023-11-27 at 17 53 19

File: packages/DateTimePickerCommon/src/CustomHeader.tsx [hunk 2]
```diff
@@ -48,23 +54,27 @@ export const CustomHeader: React.FC<CustomHeaderProps> = ({
   return (
     <S.CustomHeader>
       <Button
-        disabled={month === months[0].label && year === startYear}
-        onClick={decreaseMonth}
+        disabled={
+          isMonthYearPicker ? year === startYear : month === months[0].label && year === startYear
```
Comment (theo-mesnil) [inline packages/DateTimePickerCommon/src/CustomHeader.tsx:58]: Peut être sortir la règle pour la mettre plus haut ?

File: packages/DateTimePickerCommon/src/CustomHeader.tsx [hunk 3]
```diff
@@ -75,10 +85,14 @@ export const CustomHeader: React.FC<CustomHeaderProps> = ({
         />
       </S.Selects>
       <Button
-        disabled={month === months[months.length - 1].label && year === endYear}
-        onClick={increaseMonth}
+        disabled={
+          isMonthYearPicker
+            ? year === endYear
+            : month === months[months.length - 1].label && year === endYear
+        }
```
Comment (theo-mesnil) [inline packages/DateTimePickerCommon/src/CustomHeader.tsx:92]: Pareil ici :)

**Review by theo-mesnil — APPROVED** [review]

**Review by theo-mesnil — APPROVED** [review]
