### PR TITLE
fix: make Modal close when pressing Esc

### LINKED ISSUE #549: Can't close Modal by pressing Escape
###  Describe the bug

Can't close the Modal component by pressing <kbd>Escape</kbd>

### To Reproduce

1. Go to http://welcome-ui.com/components/modal
2. Open any modal
3. Press <kbd>Escape</kbd>

### Expected behavior

It should close when pressing <kbd>Escape</kbd>, or, at least, have an option to enable it.

### Environment

- Welcome-UI version: latest
- Browser: Chrome 79
- OS: MacOS 10.15.3

### PR DESCRIPTION
**Pull request by diegohaz**
Closes #549

### CODE REVIEW

File: packages/Modal/index.js [hunk 1]
```diff
@@ -28,11 +28,16 @@ export function Modal({
   return (
     <>
       <Portal>
-        <DialogBackdrop onClick={closeModal} {...rest}>
+        <DialogBackdrop {...rest}>
```
Comment (diegohaz) [inline packages/Modal/index.js]: `Dialog` will automatically call `hide` when clicking outside it (even if `DialogBackdrop` is not used).

**Comment by theo-mesnil** [comment]
Hello @diegohaz :)

Thanks for your contribution, we are going to test this and merge asap !

File: packages/Modal/index.js (hunk 1 above)
Comment (P1X3L) [reply packages/Modal/index.js]: Thank you for this @diegohaz, we really appreciate 👍
Thanks also for [reakit](https://github.com/reakit/reakit) it's such a great library that we really enjoy using!
